//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBRSysAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SBREntities : DbContext
    {
        public SBREntities()
            : base("name=SBREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_SBR_ATTACH> TBL_SBR_ATTACH { get; set; }
        public virtual DbSet<TBL_SBR_ATTACH_ATTR> TBL_SBR_ATTACH_ATTR { get; set; }
        public virtual DbSet<TBL_SBR_Lookup> TBL_SBR_Lookup { get; set; }
        public virtual DbSet<TBL_SBR_TestFlow> TBL_SBR_TestFlow { get; set; }
        public virtual DbSet<TBL_SBR_RD_Header> TBL_SBR_RD_Header { get; set; }
        public virtual DbSet<TBL_SBR_Dynamic_ColumnLookup> TBL_SBR_Dynamic_ColumnLookup { get; set; }
        public virtual DbSet<TBL_SBR_Dynamic_ColumnResult> TBL_SBR_Dynamic_ColumnResult { get; set; }
        public virtual DbSet<TBL_SBR_TestFlow_Steps> TBL_SBR_TestFlow_Steps { get; set; }
    }
}
