//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBRSysAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SBR_RD_Header
    {
        public System.Guid Id { get; set; }
        public System.Guid SBR_Header_Id { get; set; }
        public string SBR_Num { get; set; }
        public int Version { get; set; }
        public decimal Pulse_Width { get; set; }
        public decimal Duty_Cycle { get; set; }
        public string Wafer_ID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Requestor { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public string Attribute { get; set; }
        public string Created_By { get; set; }
        public string LastUpdated_By { get; set; }
        public string ProductName { get; set; }
        public string ApprComment { get; set; }
        public Nullable<decimal> CostAmt { get; set; }
        public string LotType { get; set; }
        public string TesterType { get; set; }
        public Nullable<int> Released_Status { get; set; }
        public string Released_Comments { get; set; }
        public Nullable<System.DateTime> Released_Date { get; set; }
        public string Released_By { get; set; }
    }
}
