//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBRSysAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SBR_Dynamic_ColumnLookup
    {
        public System.Guid Id { get; set; }
        public string DCType { get; set; }
        public string GroupSequence { get; set; }
        public string GroupName { get; set; }
        public string LabelSequence { get; set; }
        public string LabelName { get; set; }
        public string ComponentType { get; set; }
        public string DefaultValue { get; set; }
        public string Direction { get; set; }
        public string IsShow { get; set; }
        public string IsEditable { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public string Attribute { get; set; }
        public string Created_By { get; set; }
        public string LastUpdated_By { get; set; }
        public string RelationGroupName { get; set; }
    }
}
