//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBRSysAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SBR_TestFlow_Steps
    {
        public System.Guid Id { get; set; }
        public System.Guid Testflow_Id { get; set; }
        public System.Guid SBR_RD_Header_Id { get; set; }
        public Nullable<int> Step { get; set; }
        public string Current_mA { get; set; }
        public string PDRange { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public string Created_By { get; set; }
        public string LastUpdated_By { get; set; }
        public string Attribute { get; set; }
    }
}
