//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBRSysAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SBR_TestFlow
    {
        public System.Guid Id { get; set; }
        public System.Guid SBR_Header_Id { get; set; }
        public System.Guid SBR_RD_Header_Id { get; set; }
        public int Seq { get; set; }
        public string TestType { get; set; }
        public string Temperature { get; set; }
        public string Sampling_Rate { get; set; }
        public string Iop { get; set; }
        public string LogFile { get; set; }
        public string EmitCount { get; set; }
        public string EmitMap { get; set; }
        public string TpDefMap { get; set; }
        public string TestMap { get; set; }
        public int TesterNum { get; set; }
        public int WaferNum { get; set; }
        public string Comments { get; set; }
        public string TestTime { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.DateTime Last_Updated_Date { get; set; }
        public string Created_By { get; set; }
        public string LastUpdated_By { get; set; }
        public string Attribute { get; set; }
        public Nullable<bool> IsIRTest { get; set; }
    }
}
